### ISSUE TITLE
Inconsistency in the technique-mitigation relationships provided in the "x-attack.json" files.

### ISSUE THREAD

**Issue by angeorg83** [mitre/cti#151] opened 2021-02-21 19:40 UTC
We have noticed that the ics-attack.json and enterprise-attack.json files do not agree in all technique-mitigation relationships hosted in the official websites. 

Examples:
a) "M1036 - Account Use Policies" (https://collaborate.mitre.org/attackics/index.php/Mitigation/M1036): according to the website mitigates both "T0859 - Valid Accounts" and "T0822 - External Remote Services", whereas in the ics-attack.json file T0822 is missing.
b) "T0803 - Block Command Message" (https://collaborate.mitre.org/attackics/index.php/Technique/T0803): according to the website is mitigated by "M0807- Network Allowlists", "M0810 - Out-of-Band Communications Channel" and "M0814 - Static Network Configuration" whereas in the ics-attack.json file M1045 appears also as a possible mitigation:
c) T1086: present in the enterprise-attack.json file (with "url": "https://attack.mitre.org/techniques/T1086") but not presented in the website. In the file is considered to be mitigated by M1045.

Which one should be considered the "source of truth"? The files or the official websites?

**Comment by isaisabel** [comment] 2021-02-22 14:40
I will let @chrisante7 answer regarding _a_ and _b_.

For _c_ I can answer that `T1086` is revoked, and revoked objects are not displayed directly on attack.mitre.org. `T1086` was replaced with `T1059.001` and [the page on attack.mitre.org for T1086](https://attack.mitre.org/techniques/T1086) is now a redirect to `T1059.001`. [Please see our documentation on revoked and deprecated objects for more information about how revocations work](https://github.com/mitre/cti/blob/master/USAGE.md#working-with-deprecated-and-revoked-objects).

**Comment by angeorg83** [comment] 2021-02-22 14:58
Thank you @isaisabel for the prompt and to the point response!

I shall be looking forward to @chrisante7 reply regarding points (a) and (b).

**Comment by chrisante7** [comment] 2021-02-22 17:22
Hi @angeorg83, 

Examples a) and b) do seem to be bugs. The website is the so-called "source of truth" as the STIX's data is pulled from the ICS wiki. I will create a PR and update accordingly.

Thank you for finding!

**Comment by isaisabel** [comment] 2021-02-22 17:25
I should note that the website being the "source of truth" only applies to ICS. For the Enterprise and Mobile domains, attack.mitre.org is built directly from the STIX data on this repo so the STIX data is the "source of truth."

**Comment by angeorg83** [comment] 2021-02-22 17:32
Thank you @chrisante7 and @isaisabel! 

Please let us know when this PR is implemented.

**Comment by isaisabel** [comment] 2021-02-22 17:58
_a_ and _b_ fixed in #153.

**Closed by isaisabel** 2021-02-22 17:58 UTC
Labels: bug

**Comment by angeorg83** [comment] 2021-02-22 19:12
Thank you @isaisabel!

However, these were only **a few examples** of the inconsistencies noticed with the ICS mitigation relationships. 

Another example is [T0804 ](https://collaborate.mitre.org/attackics/index.php/Technique/T0804) erroneously mitigated by [M1045](https://collaborate.mitre.org/attackics/index.php/Mitigation/M1045). 

Do you mind reopening this issue so that we can post here all issues we come across? 

Thank you!

**Comment by isaisabel** [comment] 2021-02-22 19:29
Sure, if you find something else feel free to post it in this thread and I can reopen it. I'll get notified of any replies even if the issue is closed.

However, I would rather not preemptively re-open the thread before anything further gets reported just from a issue tracker cleanliness perspective.
