### ISSUE TITLE
Microsoft Defender Detection

### ISSUE THREAD

**Issue by Malthasian** [mitre/cti#210] opened 2023-04-25 20:30 UTC
Microsoft Defender reports a "Backdoor:PHP/Remoteshell.B" detection in enterprise-attack/relationship/relationship--2610bdef-0b08-46a8-94f5-cf253f11e5fc.json

(Edit: my initial assumption was incorrect)

**Comment by Malthasian** [comment] 2023-04-25 20:40
![image](https://user-images.githubusercontent.com/17813078/234398339-23f02d6d-bf30-4ce5-b921-52919bd6c162.png)

**Comment by Malthasian** [comment] 2023-04-25 20:53
[(https://www.virustotal.com/gui/file/80c4069d66a4e7dfaa37bb65e1b9dbb4fd63ff6b651be3268388df11ca24af38)](https://www.virustotal.com/gui/file/80c4069d66a4e7dfaa37bb65e1b9dbb4fd63ff6b651be3268388df11ca24af38)

![image](https://user-images.githubusercontent.com/17813078/234400984-a21279b7-c192-4921-8d44-55f973778a1b.png)

**Comment by jondricek** [comment] 2023-04-26 14:22
This regularly happens with each release of ATT&CK where it is initially deemed malicious by A/V scanners due to the nature of the content being reported in ATT&CK.

Ultimately this is a duplicate of #67, #76, and #162 (not to mention future GitHub issues as well).

Thanks for reporting it though!

**Closed as completed by jondricek** 2023-04-26 14:22 UTC
Labels: duplicate

**Comment by jim-nitterauer** [comment] 2023-10-19 20:48
We are seeing the same behavior every time we spin up a Docker instance. Is there a way to validate that the file enterprise-attack/relationship/relationship--2610bdef-0b08-46a8-94f5-cf253f11e5fc.json is actually safe? Seems like there should be a re-write or some sort of validation that this is a false positive aside from a random "trust me, its ok" post. Thanks!
